### ISSUE TITLE
Compass trying to write to --images-dir=images

### ISSUE THREAD

**Issue by jakobjames** [tedgeving/wp-bootstrap#1]
I've set the theme up following all the outlined steps.

However, when I run a 'grunt watch' command and make a small change to the stylesheet to test, Compass writes to --images-dir=images/style.css instead of the root directory

**Comment by tedgeving** [comment]
Hi, thanks for taking a look at the project.  

I noticed in the ReadMe that there was typo on line 80, it should be `$ bower install bootstrap-sass`.  
Before it was ' $ bower install boostrap-sass '  which would place the bootstrap project in the wrong directory.  

If that was  the case `grunt copy` would fail to move  the bootstrap project files to the correct directories.  Double check that the files from `wp-bootstrap/replacement files` were copied to the root of theme making sure that `Gruntfile.js, bower.json, package.json` are replaced.

Assuming Bootstrap is in the correct directory and files were copied to the correct directory 
running `npm install` and `grunt copy` again should fix the problem. 

Screen shot of correct directory structure: http://imgur.com/3koem27
